import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { 
  Music, 
  Play, 
  Pause, 
  Volume2,
  Sparkles,
  RefreshCw,
  Check,
  Settings2,
  ChevronDown
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface ThemeMusicSectionProps {
  projectId: string;
}

const MOOD_OPTIONS = [
  { id: 'dramatic', label: 'Dramatic', color: 'bg-red-500/10 text-red-600 border-red-500/30' },
  { id: 'mysterious', label: 'Mysterious', color: 'bg-purple-500/10 text-purple-600 border-purple-500/30' },
  { id: 'romantic', label: 'Romantic', color: 'bg-pink-500/10 text-pink-600 border-pink-500/30' },
  { id: 'action', label: 'Action', color: 'bg-orange-500/10 text-orange-600 border-orange-500/30' },
  { id: 'comedy', label: 'Comedy', color: 'bg-yellow-500/10 text-yellow-600 border-yellow-500/30' },
  { id: 'horror', label: 'Horror', color: 'bg-slate-500/10 text-slate-600 border-slate-500/30' },
  { id: 'inspirational', label: 'Inspirational', color: 'bg-blue-500/10 text-blue-600 border-blue-500/30' },
  { id: 'melancholic', label: 'Melancholic', color: 'bg-indigo-500/10 text-indigo-600 border-indigo-500/30' },
];

const GENRE_OPTIONS = [
  { id: 'orchestral', label: 'Orchestral' },
  { id: 'electronic', label: 'Electronic' },
  { id: 'acoustic', label: 'Acoustic' },
  { id: 'ambient', label: 'Ambient' },
  { id: 'jazz', label: 'Jazz' },
  { id: 'rock', label: 'Rock' },
  { id: 'folk', label: 'Folk' },
  { id: 'cinematic', label: 'Cinematic' },
];

export function ThemeMusicSection({ projectId }: ThemeMusicSectionProps) {
  const [selectedMood, setSelectedMood] = useState<string>('dramatic');
  const [selectedGenre, setSelectedGenre] = useState<string>('cinematic');
  const [customPrompt, setCustomPrompt] = useState('');
  const [isPlaying, setIsPlaying] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [volume, setVolume] = useState([70]);
  const [hasGenerated, setHasGenerated] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [isEditOpen, setIsEditOpen] = useState(false);

  // Auto-generate music on component mount (mockup)
  useEffect(() => {
    if (!autoGenerated) {
      setIsGenerating(true);
      const timer = setTimeout(() => {
        setIsGenerating(false);
        setHasGenerated(true);
        setAutoGenerated(true);
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerated]);

  const handleGenerate = () => {
    setIsGenerating(true);
    // Mock generation
    setTimeout(() => {
      setIsGenerating(false);
      setHasGenerated(true);
      setIsEditOpen(false);
    }, 2000);
  };

  const togglePlay = () => {
    setIsPlaying(!isPlaying);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Music className="h-5 w-5" />
          Theme & Background Music
        </CardTitle>
        <CardDescription>
          AI-generated background music for your project
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Preview Player - Always Visible */}
        <div className="rounded-lg border bg-muted/30 p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Button
                size="icon"
                variant={hasGenerated ? 'default' : 'secondary'}
                onClick={togglePlay}
                disabled={!hasGenerated || isGenerating}
              >
                {isGenerating ? (
                  <RefreshCw className="h-4 w-4 animate-spin" />
                ) : isPlaying ? (
                  <Pause className="h-4 w-4" />
                ) : (
                  <Play className="h-4 w-4" />
                )}
              </Button>
              <div>
                <p className="text-sm font-medium">
                  {isGenerating 
                    ? 'Generating theme music...'
                    : hasGenerated 
                      ? `${MOOD_OPTIONS.find(m => m.id === selectedMood)?.label} ${GENRE_OPTIONS.find(g => g.id === selectedGenre)?.label} Theme`
                      : 'No preview generated'
                  }
                </p>
                <p className="text-xs text-muted-foreground">
                  {isGenerating 
                    ? 'AI composing...' 
                    : hasGenerated 
                      ? '0:30 • AI Generated' 
                      : 'Generate to preview'
                  }
                </p>
              </div>
            </div>
            
            {/* Volume Control */}
            <div className="flex items-center gap-2">
              <Volume2 className="h-4 w-4 text-muted-foreground" />
              <Slider
                value={volume}
                onValueChange={setVolume}
                max={100}
                step={1}
                className="w-24"
              />
            </div>
          </div>

          {/* Progress Bar (mock) */}
          {hasGenerated && !isGenerating && (
            <div className="mt-3">
              <div className="h-1 w-full rounded-full bg-muted">
                <div 
                  className={cn(
                    'h-full rounded-full bg-primary transition-all',
                    isPlaying ? 'animate-pulse' : ''
                  )}
                  style={{ width: isPlaying ? '45%' : '0%' }}
                />
              </div>
            </div>
          )}
        </div>

        {/* Collapsible Edit Section */}
        <Collapsible open={isEditOpen} onOpenChange={setIsEditOpen}>
          <CollapsibleTrigger asChild>
            <Button variant="ghost" className="w-full justify-between" size="sm">
              <span className="flex items-center gap-2">
                <Settings2 className="h-4 w-4" />
                Customize Theme
              </span>
              <ChevronDown className={cn(
                "h-4 w-4 transition-transform",
                isEditOpen && "rotate-180"
              )} />
            </Button>
          </CollapsibleTrigger>
          
          <CollapsibleContent className="space-y-4 pt-4">
            {/* Mood Selection */}
            <div className="space-y-3">
              <Label>Project Mood</Label>
              <div className="flex flex-wrap gap-2">
                {MOOD_OPTIONS.map((mood) => (
                  <button
                    key={mood.id}
                    onClick={() => setSelectedMood(mood.id)}
                    className={cn(
                      'rounded-full border px-3 py-1.5 text-sm font-medium transition-all',
                      mood.color,
                      selectedMood === mood.id 
                        ? 'ring-2 ring-primary ring-offset-2' 
                        : 'opacity-70 hover:opacity-100'
                    )}
                  >
                    {selectedMood === mood.id && (
                      <Check className="mr-1 inline h-3 w-3" />
                    )}
                    {mood.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Genre Selection */}
            <div className="space-y-3">
              <Label>Music Genre</Label>
              <div className="flex flex-wrap gap-2">
                {GENRE_OPTIONS.map((genre) => (
                  <Badge
                    key={genre.id}
                    variant={selectedGenre === genre.id ? 'default' : 'outline'}
                    className={cn(
                      'cursor-pointer transition-all',
                      selectedGenre === genre.id 
                        ? '' 
                        : 'hover:bg-primary/10'
                    )}
                    onClick={() => setSelectedGenre(genre.id)}
                  >
                    {genre.label}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Custom Prompt */}
            <div className="space-y-2">
              <Label>Custom Music Description (Optional)</Label>
              <Textarea
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                placeholder="Describe additional details for the music... e.g., 'slow build-up with strings, rising tension'"
                className="resize-none"
                rows={2}
              />
            </div>

            {/* Regenerate Button */}
            <Button 
              onClick={handleGenerate} 
              disabled={isGenerating}
              className="w-full"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Regenerate Theme
                </>
              )}
            </Button>
          </CollapsibleContent>
        </Collapsible>

        {/* Info Note */}
        <div className="flex items-start gap-2 rounded-lg border border-primary/20 bg-primary/5 p-3">
          <Sparkles className="mt-0.5 h-4 w-4 text-primary shrink-0" />
          <p className="text-sm text-muted-foreground">
            This theme will be used as the default background music for your animatic.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
