import { useEffect, useState, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Header } from '@/components/layout/Header';
import { ShotGrid } from '@/components/shots/ShotGrid';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useProject } from '@/contexts/ProjectContext';
import { useToast } from '@/hooks/use-toast';
import { ArrowLeft, ArrowRight, Layers, Loader2 } from 'lucide-react';
import { CameraAngle, CameraMovement, Framing } from '@/types';

export default function ShotList() {
  const { projectId } = useParams<{ projectId: string }>();
  const { 
    projects, 
    scenes, 
    shots,
    frames,
    setCurrentProject,
    addShot,
    updateShot,
    deleteShot
  } = useProject();
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationProgress, setGenerationProgress] = useState({ current: 0, total: 0 });
  const hasAutoGenerated = useRef(false);

  const project = projects.find(p => p.id === projectId);
  const projectScenes = scenes.filter(s => s.projectId === projectId);
  const projectShots = shots.filter(s => s.projectId === projectId);
  const projectFrames = frames.filter(f => 
    projectScenes.some(s => s.id === f.sceneId)
  );

  const autoGenerateShots = async () => {
    if (projectFrames.length === 0 || projectShots.length > 0 || isGenerating) return;
    
    setIsGenerating(true);
    const totalToGenerate = projectFrames.length;
    setGenerationProgress({ current: 0, total: totalToGenerate });
    
    toast({ 
      title: 'Generating shot list...', 
      description: `Creating ${totalToGenerate} shots from storyboard frames.` 
    });

    const cameraAngles: CameraAngle[] = ['eye-level', 'high-angle', 'low-angle', 'over-the-shoulder'];
    const cameraMovements: CameraMovement[] = ['static', 'pan-left', 'pan-right', 'dolly-in', 'tracking'];
    const framings: Framing[] = ['wide', 'medium', 'medium-close-up', 'close-up'];

    let shotNumber = 1;
    let generatedCount = 0;

    for (const frame of projectFrames) {
      // Create a shot for each frame with varied camera settings
      addShot({
        projectId: projectId!,
        shotNumber: shotNumber++,
        frameId: frame.id,
        sceneId: frame.sceneId,
        cameraAngle: cameraAngles[generatedCount % cameraAngles.length],
        lensType: ['24mm', '35mm', '50mm', '85mm'][generatedCount % 4],
        cameraMovement: cameraMovements[generatedCount % cameraMovements.length],
        framing: framings[generatedCount % framings.length],
        notes: frame.description || '',
      });

      generatedCount++;
      setGenerationProgress({ current: generatedCount, total: totalToGenerate });
      
      // Small delay to show progress
      await new Promise(resolve => setTimeout(resolve, 50));
    }

    setIsGenerating(false);
    setGenerationProgress({ current: 0, total: 0 });
    toast({ 
      title: 'Shot list ready!', 
      description: `Created ${generatedCount} shots from your storyboard.` 
    });
  };

  useEffect(() => {
    if (project) {
      setCurrentProject(project);
    }
  }, [project, setCurrentProject]);

  // Auto-generate shots when visiting page with frames but no shots
  useEffect(() => {
    if (
      project && 
      projectFrames.length > 0 && 
      projectShots.length === 0 && 
      !isGenerating && 
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      autoGenerateShots();
    }
  }, [project, projectFrames.length, projectShots.length, isGenerating]);

  if (!project) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <p className="text-muted-foreground">Loading project...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30">
      <Header />
      
      <main className="container mx-auto px-4 py-8">
        {/* Breadcrumb */}
        <div className="mb-6 flex items-center justify-between">
          <div>
            <Link 
              to={`/project/${projectId}/storyboard`}
              className="mb-2 inline-flex items-center text-sm text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Storyboard
            </Link>
            <h1 className="text-2xl font-bold">{project.title} — Shot List</h1>
            <p className="text-muted-foreground">
              {projectShots.length} shots • {projectScenes.length} scenes
              {isGenerating && ' • Generating...'}
            </p>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" asChild>
              <Link to={`/project/${projectId}/storyboard`}>
                <Layers className="mr-2 h-4 w-4" />
                Storyboard
              </Link>
            </Button>
            <Button className="gradient-primary" asChild disabled={isGenerating}>
              <Link to={`/project/${projectId}/animatic`}>
                Animatic
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>

        {/* Generation Progress Banner */}
        {isGenerating && generationProgress.total > 0 && (
          <div className="mb-6 rounded-lg border border-primary/20 bg-primary/5 p-4">
            <div className="flex items-center justify-between text-sm">
              <span className="flex items-center gap-2 font-medium text-primary">
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating shots from storyboard...
              </span>
              <span className="font-medium">
                {generationProgress.current} / {generationProgress.total}
              </span>
            </div>
            <Progress 
              value={(generationProgress.current / generationProgress.total) * 100} 
              className="mt-2 h-2" 
            />
          </div>
        )}

        {/* Shot Grid */}
        <ShotGrid
          shots={projectShots}
          frames={projectFrames}
          projectId={projectId!}
          sceneIds={projectScenes.map(s => s.id)}
          onAddShot={addShot}
          onUpdateShot={updateShot}
          onDeleteShot={deleteShot}
        />
      </main>
    </div>
  );
}
