import { useEffect, useState, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Header } from '@/components/layout/Header';
import { StoryboardCanvas } from '@/components/storyboard/StoryboardCanvas';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useProject } from '@/contexts/ProjectContext';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { ArrowLeft, ArrowRight, Layers, Loader2 } from 'lucide-react';
import { Scene } from '@/types';

export default function Storyboard() {
  const { projectId } = useParams<{ projectId: string }>();
  const { 
    projects, 
    scenes, 
    frames,
    shots,
    setCurrentProject,
    addFrame,
    updateFrame,
    deleteFrame
  } = useProject();
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationProgress, setGenerationProgress] = useState({ current: 0, total: 0 });
  const hasAutoGenerated = useRef(false);

  const project = projects.find(p => p.id === projectId);
  const projectScenes = scenes.filter(s => s.projectId === projectId);
  const projectFrames = frames.filter(f => 
    projectScenes.some(s => s.id === f.sceneId) || f.sceneId === ''
  );
  const projectShots = shots.filter(s => s.projectId === projectId);

  const generateFrameImage = async (
    scene: Scene, 
    frameDescription: string,
    cameraAngle: string,
    style: string
  ): Promise<string | null> => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-storyboard-frame', {
        body: {
          sceneDescription: `${scene.heading}: ${frameDescription}`,
          style,
          cameraAngle,
          lighting: scene.lighting || 'natural lighting',
          characters: scene.characters || [],
        },
      });

      if (error) throw error;
      return data?.imageUrl || null;
    } catch (error) {
      console.error('Error generating frame image:', error);
      return null;
    }
  };

  const autoGenerateStoryboard = async () => {
    if (projectScenes.length === 0 || projectFrames.length > 0 || isGenerating) return;
    
    setIsGenerating(true);
    const totalToGenerate = projectScenes.length * 2;
    setGenerationProgress({ current: 0, total: totalToGenerate });
    
    toast({ 
      title: 'Generating storyboard...', 
      description: `Creating ${totalToGenerate} AI-generated frames.` 
    });

    let frameNumber = 1;
    let generatedCount = 0;

    for (const scene of projectScenes) {
      const framesPerScene = 2;
      const cameraAngles = ['wide', 'medium', 'close-up'];
      
      for (let i = 0; i < framesPerScene; i++) {
        const cameraAngle = cameraAngles[i % cameraAngles.length];
        const frameDesc = i === 0 
          ? `Establishing shot: ${scene.description?.slice(0, 150) || 'Scene overview'}`
          : `Action shot: ${scene.dialogue?.[0]?.text || scene.description?.slice(0, 150) || 'Character moment'}`;
        
        const newFrame = addFrame({
          sceneId: scene.id,
          frameNumber: frameNumber++,
          imageUrl: undefined,
          description: frameDesc,
          duration: 3,
          cameraAngle,
          cameraMovement: 'static',
          notes: '',
          style: 'anime',
          isGenerating: true,
        });

        const imageUrl = await generateFrameImage(scene, frameDesc, cameraAngle, 'anime');
        
        updateFrame(newFrame.id, {
          imageUrl: imageUrl || '/placeholder.svg',
          isGenerating: false,
        });

        generatedCount++;
        setGenerationProgress({ current: generatedCount, total: totalToGenerate });
      }
    }

    setIsGenerating(false);
    setGenerationProgress({ current: 0, total: 0 });
    toast({ 
      title: 'Storyboard ready!', 
      description: `Created ${generatedCount} AI-generated frames.` 
    });
  };

  useEffect(() => {
    if (project) {
      setCurrentProject(project);
    }
  }, [project, setCurrentProject]);

  // Auto-generate storyboard when visiting page with scenes but no frames
  useEffect(() => {
    if (
      project && 
      projectScenes.length > 0 && 
      projectFrames.length === 0 && 
      !isGenerating && 
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      autoGenerateStoryboard();
    }
  }, [project, projectScenes.length, projectFrames.length, isGenerating]);

  if (!project) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <p className="text-muted-foreground">Loading project...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30">
      <Header />
      
      <main className="container mx-auto px-4 py-8">
        {/* Breadcrumb */}
        <div className="mb-6 flex items-center justify-between">
          <div>
            <Link 
              to={`/project/${projectId}`}
              className="mb-2 inline-flex items-center text-sm text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Project
            </Link>
            <h1 className="text-2xl font-bold">{project.title} — Storyboard</h1>
            <p className="text-muted-foreground">
              {projectScenes.length} scenes • {projectFrames.length} frames
              {isGenerating && ' • Generating...'}
            </p>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" asChild>
              <Link to={`/project/${projectId}?tab=scenes`}>
                <Layers className="mr-2 h-4 w-4" />
                Scenes
              </Link>
            </Button>
            <Button className="gradient-primary" asChild disabled={isGenerating}>
              <Link to={`/project/${projectId}/shots`}>
                Generate Shots
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>

        {/* Generation Progress Banner */}
        {isGenerating && generationProgress.total > 0 && (
          <div className="mb-6 rounded-lg border border-primary/20 bg-primary/5 p-4">
            <div className="flex items-center justify-between text-sm">
              <span className="flex items-center gap-2 font-medium text-primary">
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating AI storyboard frames...
              </span>
              <span className="font-medium">
                {generationProgress.current} / {generationProgress.total}
              </span>
            </div>
            <Progress 
              value={(generationProgress.current / generationProgress.total) * 100} 
              className="mt-2 h-2" 
            />
          </div>
        )}

        {/* Canvas */}
        <StoryboardCanvas
          frames={projectFrames}
          scenes={projectScenes}
          shots={projectShots}
          projectId={projectId!}
          onAddFrame={addFrame}
          onUpdateFrame={updateFrame}
          onDeleteFrame={deleteFrame}
        />
      </main>
    </div>
  );
}
